name             'secrets-lwrp'
maintainer       'Steven Spriggs'
maintainer_email 'steven.spriggs@mail.wvu.edu'
license          'All rights reserved'
description      'Installs/Configures secrets-lwrp'
long_description 'Installs/Configures secrets-lwrp'
version          '0.1.0'
